### ISSUE TITLE
Unexpected EOF error

### ISSUE THREAD

**Issue by Konbu845** [robinovitch61/webtoon-dl#4]
Hello, firstly, I want to thank you very much for this command! It worked well, sorting through the series but then I received an error "unexpected EOF". I am new to using codes and stuff so I couldn't figure out the problem. I used the prompt for an Indonesian webtoon version on Windows Terminal x64 and the latest version of webtoon-dl. I've tried running the prompt couple of times but the issue persist.

[error.txt](https://github.com/robinovitch61/webtoon-dl/files/14431027/error.txt)

**Comment by robinovitch61** [comment]
Hey @Konbu845 , thanks for the issue. The error likely indicates some sort of resource exhaustion on your machine, possibly out of memory. Can you retry with
```
webtoon-dl --eps-per-file=5 "https://www.webtoons.com/id/action/how-to-fight/list?title_no=1992"
```
This flag "episodes per file" will checkpoint your work more often, i.e. save a PDF every 5 episodes instead of the default 10.

If you get the error, then at least it's likely you'll have checkpointed some files and can use `--min-ep=` to start off from where you last checkpointed. See the [README](https://github.com/robinovitch61/webtoon-dl) for full examples.

**Comment by Konbu845** [comment]
Oh, hey, it's fine. I ran it again this time with windows powershell as administrator with this `webtoon-dl --min-ep=10 --max-ep=20 --eps-per-file=1` and it works!! Thank you for your help!
