### ISSUE TITLE
Where do files save to?

### ISSUE THREAD

**Issue by MatDelaz** [robinovitch61/webtoon-dl#9]
Hello, thank you for your work, it seems to work but I can't find the files once it's finished :/
Could you help me?
thank you

**Comment by robinovitch61** [comment]
No stupid questions :) can you post the output of the command you run? For example:
```
❯ webtoon-dl "https://www.webtoons.com/en/fantasy/tower-of-god/season-3-ep-199/viewer?title_no=95&episode_no=617"
found 119 total image links across 1 episodes
saving into 1 files with max of 10 episodes per file
saving episodes 617 through 617: added page 1/119
saving episodes 617 through 617: added page 2/119
saving episodes 617 through 617: added page 3/119
...I deleted these middle lines
saving episodes 617 through 617: added page 119/119
saved to en-fantasy-tower-of-god-season-3-ep-199-epNo617.pdf
```
since I ran this command with my terminal in the "Downloads" folder, and it says `saved to en-fantasy-tower-of-god-season-3-ep-199-epNo617.pdf`, that means the file will be in `Downloads/en-fantasy-tower-of-god-season-3-ep-199-epNo617.pdf`

If you're on mac/linux, you can tell what directory your terminal is in by running `pwd`. On windows, the equivalent is running `cd`.

**Comment by MatDelaz** [comment]
pc was broken, thx a lot for your answer
